### ISSUE TITLE
Card scanning isn't working

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/KLBFAX#11]
I scanned my card this morning and the name page didn't appear.

Also, I am owed 20 points for arriving early

**Comment by mscroggs** [comment]
all input from the keypad is being ignored.

**Comment by afiodorov** [comment]
Yeah, not surprised: I can't check point allocations on my computer - so my changes went in untested. I'll need to add the ability to check point allocations in a development mode (should be fairly easy) and then I will make sure it works on the Pi. I will look into this this evening.

**Comment by afiodorov** [comment]
Heh, you can always just run the Pi on the previous stable commit until I get round to it :)

**Comment by afiodorov** [comment]
Unassigned until I'm actually working on it.

**Comment by mscroggs** [comment]
Fixed it.

ceefax.py was checking that /home/pi/cards/{input} was a file then reading the name and house from {input} without the /home/pi/cards/
