### ISSUE TITLE
We need an ASCII picture of the contributors

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/KLBFAX#17]
I would like a new page which contains a picture of Adam, Gin, Sam, Tom and me.

**Comment by Giannie** [comment]
Hilarious. I agree. Can mine just be beard and glasses please?

**Comment by SamBrown49** [comment]
Does anyone have a script to auto-generate ASCII art?

**Comment by mscroggs** [comment]
There must be one around.

Ideally Gin's beard and glasses would be spinning

**Comment by mscroggs** [comment]
I have added very crude pictures of everyone to page 777
