### ISSUE TITLE
Page loading mechanism seems to be not very good for testing

### ISSUE THREAD

**Issue by afiodorov** [mscroggs/KLBFAX#2]
I wanted to add a page, but I feel like some preliminary work ought to be done for adding pages to be a bit less painful.

Some things which I would like to address:
- Pages that throw exceptions shouldn't be shown
- I should be able to navigate to any page in order to test it while developing it
- Each page should have a boolean disable flag so that it can be silently tested but not displayed

I suggest making a PageBase class with

.content
.isEnabled
.tag
.show()

attributes.

Each page should inherit PageBase and override the relevant bit.

Then add a PageFactory class with
.random()
method, which will return a random Page.

and finally,

PageFactory.random().show()

should be called to display the page.

In testing,

PageFactory.getPage("000").show() could be deployed.

Of course there could be many other solutions to the problem I outlined. If you think it's a problem of course. I would be more than happy to provide the code for this if you think it's worth doing.

**Comment by mscroggs** [comment]
Page class and PageFactory class should now be working and you can type the page number in for testing
