### ISSUE TITLE
Scrolling on the letters page?

### ISSUE THREAD

**Issue by afiodorov** [mscroggs/KLBFAX#8]
With emails getting longer and longer it's quite disappointing that we can't actually read them when they don't fit (or can we?).

Would be nice to enhance the interface somewhat (just adding scrolling will do, but future work could include jumping through letters).

**Comment by afiodorov** [comment]
I won't be able to attend to this until the end of June - but I volunteer to do it then if you won't attend to this.

**Comment by mscroggs** [comment]
The letters page is now 21 letters pages, each continuing from the last one. They can be navigated between by typing 201, 202 etc.
